### ISSUE TITLE
Make it clear that notebooks require Azure Maps S1 plan

### ISSUE THREAD

**Issue by kartben** [5h15h/Azure-Maps-Jupyter-Notebooks#2]
It would be good to add a note that an S1 subscription is required for these examples, and that they won't work if the provided key is for an S0.

**Comment by 5h15h** [comment]
thanks for pointing that out … I've not added the Readme yet and will do so in there

**Comment by 5h15h** [comment]
created and updated Readme with information

**Comment by kartben** [comment]
Mmmh actually I was thinking that the information would be useful to have in the notebooks themselves, after all aren't they like READMEs on steroids? :) But good thing to have a proper README in place as well, just to make sure the Github repo as a nice look & feel :)
